"""Seed recipe data for Meal Planning Amp.

Each recipe includes full ingredient lists with quantities, units, and
shopping categories, plus per-serving macros and cost estimates (GBP).
"""

RECIPES = [
    # ── Portable / Prep-Ahead Breakfasts ──────────────────────────────
    {
        "name": "Overnight Protein Oats",
        "meal_type": "breakfast",
        "cooking_method": "prep-ahead",
        "servings": 1,
        "prep_minutes": 5,
        "cook_minutes": 0,
        "calories": 450,
        "protein": 35.0,
        "carbs": 52.0,
        "fat": 12.0,
        "fibre": 8.0,
        "cost_per_serving": 1.20,
        "tags": ["high-protein", "portable", "prep-ahead"],
        "instructions": "Mix oats, protein powder, yogurt and milk in a jar. Refrigerate overnight. Top with berries in the morning.",
        "ingredients": [
            ("rolled oats", 60, "g", "pantry"),
            ("protein powder", 30, "g", "pantry"),
            ("Greek yogurt", 100, "g", "dairy"),
            ("whole milk", 100, "ml", "dairy"),
            ("mixed berries", 80, "g", "produce"),
            ("honey", 1, "tsp", "pantry"),
        ],
    },
    {
        "name": "Egg Muffin Cups",
        "meal_type": "breakfast",
        "cooking_method": "prep-ahead",
        "servings": 1,
        "prep_minutes": 10,
        "cook_minutes": 20,
        "calories": 280,
        "protein": 24.0,
        "carbs": 6.0,
        "fat": 18.0,
        "fibre": 2.0,
        "cost_per_serving": 0.90,
        "tags": ["high-protein", "portable", "low-carb", "prep-ahead"],
        "instructions": "Whisk eggs with spinach, cheese and ham. Pour into greased muffin tin. Bake at 180°C for 20 mins. Store in fridge, reheat in microwave.",
        "ingredients": [
            ("eggs", 2, "whole", "dairy"),
            ("baby spinach", 30, "g", "produce"),
            ("cheddar cheese", 20, "g", "dairy"),
            ("ham", 30, "g", "meat"),
            ("salt", 1, "pinch", "spices"),
            ("black pepper", 1, "pinch", "spices"),
        ],
    },
    {
        "name": "Greek Yogurt & Granola Pot",
        "meal_type": "breakfast",
        "cooking_method": "prep-ahead",
        "servings": 1,
        "prep_minutes": 3,
        "cook_minutes": 0,
        "calories": 380,
        "protein": 28.0,
        "carbs": 42.0,
        "fat": 10.0,
        "fibre": 4.0,
        "cost_per_serving": 1.50,
        "tags": ["high-protein", "portable", "no-cook"],
        "instructions": "Layer yogurt, granola and fruit in a pot. Drizzle with honey. Seal and refrigerate.",
        "ingredients": [
            ("Greek yogurt", 200, "g", "dairy"),
            ("granola", 50, "g", "pantry"),
            ("blueberries", 60, "g", "produce"),
            ("honey", 1, "tsp", "pantry"),
        ],
    },
    {
        "name": "Peanut Butter Banana Overnight Oats",
        "meal_type": "breakfast",
        "cooking_method": "prep-ahead",
        "servings": 1,
        "prep_minutes": 5,
        "cook_minutes": 0,
        "calories": 480,
        "protein": 22.0,
        "carbs": 60.0,
        "fat": 18.0,
        "fibre": 7.0,
        "cost_per_serving": 0.90,
        "tags": ["high-protein", "portable", "prep-ahead"],
        "instructions": "Mix oats, milk, peanut butter and chia seeds. Refrigerate overnight. Top with sliced banana.",
        "ingredients": [
            ("rolled oats", 60, "g", "pantry"),
            ("whole milk", 150, "ml", "dairy"),
            ("peanut butter", 30, "g", "pantry"),
            ("chia seeds", 10, "g", "pantry"),
            ("banana", 1, "whole", "produce"),
        ],
    },
    {
        "name": "Protein Banana Pancakes",
        "meal_type": "breakfast",
        "cooking_method": "prep-ahead",
        "servings": 1,
        "prep_minutes": 5,
        "cook_minutes": 10,
        "calories": 400,
        "protein": 32.0,
        "carbs": 45.0,
        "fat": 10.0,
        "fibre": 5.0,
        "cost_per_serving": 1.00,
        "tags": ["high-protein", "portable", "prep-ahead"],
        "instructions": "Blend banana, eggs, oats and protein powder. Cook small pancakes in a non-stick pan. Cool, stack and refrigerate. Reheat in microwave.",
        "ingredients": [
            ("banana", 1, "whole", "produce"),
            ("eggs", 2, "whole", "dairy"),
            ("rolled oats", 40, "g", "pantry"),
            ("protein powder", 25, "g", "pantry"),
            ("coconut oil", 1, "tsp", "pantry"),
        ],
    },
    # ── Home / Fresh Breakfasts ───────────────────────────────────────
    {
        "name": "Shakshuka",
        "meal_type": "breakfast",
        "cooking_method": "fresh",
        "servings": 2,
        "prep_minutes": 10,
        "cook_minutes": 20,
        "calories": 380,
        "protein": 20.0,
        "carbs": 28.0,
        "fat": 22.0,
        "fibre": 6.0,
        "cost_per_serving": 1.80,
        "tags": ["vegetarian", "high-iron"],
        "instructions": "Sauté onion, peppers and garlic. Add tinned tomatoes, cumin and paprika. Simmer 10 mins. Make wells, crack in eggs, cover and cook until set. Serve with crusty bread.",
        "ingredients": [
            ("eggs", 4, "whole", "dairy"),
            ("tinned chopped tomatoes", 400, "g", "pantry"),
            ("red pepper", 1, "whole", "produce"),
            ("onion", 1, "whole", "produce"),
            ("garlic clove", 2, "whole", "produce"),
            ("ground cumin", 1, "tsp", "spices"),
            ("smoked paprika", 1, "tsp", "spices"),
            ("olive oil", 1, "tbsp", "pantry"),
            ("crusty bread", 2, "slice", "bakery"),
        ],
    },
    {
        "name": "Avocado & Eggs on Sourdough",
        "meal_type": "breakfast",
        "cooking_method": "fresh",
        "servings": 2,
        "prep_minutes": 5,
        "cook_minutes": 5,
        "calories": 420,
        "protein": 18.0,
        "carbs": 32.0,
        "fat": 26.0,
        "fibre": 8.0,
        "cost_per_serving": 2.20,
        "tags": ["vegetarian", "omega-3"],
        "instructions": "Toast sourdough. Mash avocado with lemon, salt and chilli. Poach or fry eggs. Assemble.",
        "ingredients": [
            ("eggs", 4, "whole", "dairy"),
            ("avocado", 1, "whole", "produce"),
            ("sourdough bread", 4, "slice", "bakery"),
            ("lemon", 0.5, "whole", "produce"),
            ("chilli flakes", 1, "pinch", "spices"),
            ("olive oil", 1, "tsp", "pantry"),
        ],
    },
    {
        "name": "Smoked Salmon Scrambled Eggs",
        "meal_type": "breakfast",
        "cooking_method": "fresh",
        "servings": 2,
        "prep_minutes": 5,
        "cook_minutes": 5,
        "calories": 400,
        "protein": 32.0,
        "carbs": 24.0,
        "fat": 20.0,
        "fibre": 2.0,
        "cost_per_serving": 3.00,
        "tags": ["high-protein", "omega-3", "high-iron"],
        "instructions": "Scramble eggs gently with butter. Fold in smoked salmon and chives. Serve on toast.",
        "ingredients": [
            ("eggs", 4, "whole", "dairy"),
            ("smoked salmon", 100, "g", "fish"),
            ("butter", 15, "g", "dairy"),
            ("fresh chives", 1, "tbsp", "produce"),
            ("sourdough bread", 4, "slice", "bakery"),
        ],
    },
    {
        "name": "Porridge with Nuts & Seeds",
        "meal_type": "breakfast",
        "cooking_method": "fresh",
        "servings": 2,
        "prep_minutes": 2,
        "cook_minutes": 8,
        "calories": 380,
        "protein": 14.0,
        "carbs": 48.0,
        "fat": 16.0,
        "fibre": 7.0,
        "cost_per_serving": 0.80,
        "tags": ["vegetarian", "high-fibre"],
        "instructions": "Cook oats with milk and a pinch of salt. Top with mixed nuts, seeds and a drizzle of honey.",
        "ingredients": [
            ("rolled oats", 80, "g", "pantry"),
            ("whole milk", 300, "ml", "dairy"),
            ("mixed nuts", 30, "g", "pantry"),
            ("mixed seeds", 15, "g", "pantry"),
            ("honey", 1, "tsp", "pantry"),
            ("salt", 1, "pinch", "spices"),
        ],
    },
    {
        "name": "Berry Smoothie Bowl",
        "meal_type": "breakfast",
        "cooking_method": "fresh",
        "servings": 2,
        "prep_minutes": 10,
        "cook_minutes": 0,
        "calories": 350,
        "protein": 24.0,
        "carbs": 46.0,
        "fat": 8.0,
        "fibre": 6.0,
        "cost_per_serving": 2.00,
        "tags": ["vegetarian", "high-protein"],
        "instructions": "Blend frozen berries, banana, yogurt and protein powder until thick. Pour into bowls, top with granola and fresh fruit.",
        "ingredients": [
            ("frozen mixed berries", 200, "g", "frozen"),
            ("banana", 1, "whole", "produce"),
            ("Greek yogurt", 150, "g", "dairy"),
            ("protein powder", 30, "g", "pantry"),
            ("granola", 40, "g", "pantry"),
        ],
    },
    # ── Lunches ───────────────────────────────────────────────────────
    {
        "name": "Chicken & Avocado Wrap",
        "meal_type": "lunch",
        "cooking_method": "fresh",
        "servings": 1,
        "prep_minutes": 10,
        "cook_minutes": 0,
        "calories": 450,
        "protein": 32.0,
        "carbs": 38.0,
        "fat": 20.0,
        "fibre": 6.0,
        "cost_per_serving": 2.50,
        "tags": ["high-protein"],
        "instructions": "Shred leftover or rotisserie chicken. Layer in a tortilla with avocado, salad leaves and mayo. Roll tightly.",
        "ingredients": [
            ("cooked chicken breast", 120, "g", "meat"),
            ("flour tortilla", 1, "whole", "bakery"),
            ("avocado", 0.5, "whole", "produce"),
            ("mixed salad leaves", 30, "g", "produce"),
            ("mayonnaise", 1, "tbsp", "pantry"),
            ("lemon", 0.25, "whole", "produce"),
        ],
    },
    {
        "name": "Lentil & Sweet Potato Soup",
        "meal_type": "lunch",
        "cooking_method": "batch",
        "servings": 4,
        "prep_minutes": 10,
        "cook_minutes": 30,
        "calories": 320,
        "protein": 16.0,
        "carbs": 48.0,
        "fat": 6.0,
        "fibre": 10.0,
        "cost_per_serving": 1.00,
        "tags": ["vegan", "high-fibre", "high-iron", "freezable"],
        "instructions": "Sauté onion and garlic. Add diced sweet potato, lentils, stock and cumin. Simmer 25 mins. Blend until smooth.",
        "ingredients": [
            ("red lentils", 150, "g", "pantry"),
            ("sweet potato", 300, "g", "produce"),
            ("onion", 1, "whole", "produce"),
            ("garlic clove", 2, "whole", "produce"),
            ("vegetable stock", 800, "ml", "pantry"),
            ("ground cumin", 1, "tsp", "spices"),
            ("olive oil", 1, "tbsp", "pantry"),
        ],
    },
    {
        "name": "Tuna Niçoise Salad",
        "meal_type": "lunch",
        "cooking_method": "fresh",
        "servings": 1,
        "prep_minutes": 15,
        "cook_minutes": 10,
        "calories": 400,
        "protein": 34.0,
        "carbs": 28.0,
        "fat": 18.0,
        "fibre": 5.0,
        "cost_per_serving": 2.80,
        "tags": ["high-protein", "omega-3", "gluten-free"],
        "instructions": "Boil new potatoes and green beans until tender. Arrange with tinned tuna, halved eggs, olives and tomatoes. Dress with olive oil and lemon.",
        "ingredients": [
            ("tinned tuna", 120, "g", "pantry"),
            ("eggs", 2, "whole", "dairy"),
            ("new potatoes", 100, "g", "produce"),
            ("green beans", 60, "g", "produce"),
            ("cherry tomatoes", 60, "g", "produce"),
            ("black olives", 20, "g", "pantry"),
            ("olive oil", 1, "tbsp", "pantry"),
            ("lemon", 0.5, "whole", "produce"),
        ],
    },
    {
        "name": "Grilled Halloumi Grain Bowl",
        "meal_type": "lunch",
        "cooking_method": "fresh",
        "servings": 1,
        "prep_minutes": 10,
        "cook_minutes": 15,
        "calories": 480,
        "protein": 24.0,
        "carbs": 52.0,
        "fat": 20.0,
        "fibre": 8.0,
        "cost_per_serving": 2.50,
        "tags": ["vegetarian", "high-fibre"],
        "instructions": "Cook couscous. Grill halloumi slices. Toss couscous with roasted veg, chickpeas and lemon dressing. Top with halloumi.",
        "ingredients": [
            ("halloumi", 80, "g", "dairy"),
            ("couscous", 70, "g", "pantry"),
            ("tinned chickpeas", 80, "g", "pantry"),
            ("roasted red peppers", 50, "g", "pantry"),
            ("cucumber", 60, "g", "produce"),
            ("lemon", 0.5, "whole", "produce"),
            ("olive oil", 1, "tbsp", "pantry"),
        ],
    },
    {
        "name": "Salmon & Edamame Rice Bowl",
        "meal_type": "lunch",
        "cooking_method": "fresh",
        "servings": 1,
        "prep_minutes": 10,
        "cook_minutes": 15,
        "calories": 520,
        "protein": 34.0,
        "carbs": 54.0,
        "fat": 18.0,
        "fibre": 6.0,
        "cost_per_serving": 3.50,
        "tags": ["high-protein", "omega-3"],
        "instructions": "Cook rice. Pan-fry salmon fillet. Arrange rice, salmon, edamame, avocado slices and pickled ginger. Drizzle with soy and sesame.",
        "ingredients": [
            ("salmon fillet", 120, "g", "fish"),
            ("basmati rice", 75, "g", "pantry"),
            ("edamame beans", 60, "g", "frozen"),
            ("avocado", 0.5, "whole", "produce"),
            ("soy sauce", 1, "tbsp", "pantry"),
            ("sesame oil", 1, "tsp", "pantry"),
            ("sesame seeds", 1, "tsp", "pantry"),
        ],
    },
    {
        "name": "Spiced Chickpea & Feta Salad",
        "meal_type": "lunch",
        "cooking_method": "fresh",
        "servings": 1,
        "prep_minutes": 10,
        "cook_minutes": 5,
        "calories": 420,
        "protein": 20.0,
        "carbs": 40.0,
        "fat": 22.0,
        "fibre": 10.0,
        "cost_per_serving": 1.80,
        "tags": ["vegetarian", "high-fibre", "high-iron"],
        "instructions": "Warm chickpeas in a pan with cumin and paprika. Toss with cucumber, tomatoes, red onion and crumbled feta. Dress with olive oil and lemon.",
        "ingredients": [
            ("tinned chickpeas", 200, "g", "pantry"),
            ("feta cheese", 50, "g", "dairy"),
            ("cucumber", 80, "g", "produce"),
            ("cherry tomatoes", 80, "g", "produce"),
            ("red onion", 0.5, "whole", "produce"),
            ("ground cumin", 0.5, "tsp", "spices"),
            ("smoked paprika", 0.5, "tsp", "spices"),
            ("olive oil", 1, "tbsp", "pantry"),
            ("lemon", 0.5, "whole", "produce"),
        ],
    },
    {
        "name": "Egg Fried Rice",
        "meal_type": "lunch",
        "cooking_method": "fresh",
        "servings": 2,
        "prep_minutes": 5,
        "cook_minutes": 10,
        "calories": 380,
        "protein": 14.0,
        "carbs": 52.0,
        "fat": 12.0,
        "fibre": 3.0,
        "cost_per_serving": 1.00,
        "tags": ["vegetarian", "quick"],
        "instructions": "Stir-fry cold leftover rice in sesame oil. Push aside, scramble eggs in the pan. Mix together with peas, soy sauce and spring onions.",
        "ingredients": [
            ("basmati rice", 150, "g", "pantry"),
            ("eggs", 3, "whole", "dairy"),
            ("frozen peas", 80, "g", "frozen"),
            ("spring onions", 3, "whole", "produce"),
            ("soy sauce", 2, "tbsp", "pantry"),
            ("sesame oil", 1, "tsp", "pantry"),
        ],
    },
    {
        "name": "BLT on Sourdough",
        "meal_type": "lunch",
        "cooking_method": "fresh",
        "servings": 1,
        "prep_minutes": 5,
        "cook_minutes": 5,
        "calories": 450,
        "protein": 18.0,
        "carbs": 36.0,
        "fat": 26.0,
        "fibre": 3.0,
        "cost_per_serving": 2.00,
        "tags": ["quick"],
        "instructions": "Grill bacon until crispy. Toast sourdough. Layer with lettuce, tomato, mayo and bacon.",
        "ingredients": [
            ("back bacon", 3, "rashers", "meat"),
            ("sourdough bread", 2, "slice", "bakery"),
            ("lettuce", 30, "g", "produce"),
            ("tomato", 1, "whole", "produce"),
            ("mayonnaise", 1, "tbsp", "pantry"),
        ],
    },
    # ── Batch-Cook Dinners ────────────────────────────────────────────
    {
        "name": "Chicken Tikka Masala",
        "meal_type": "dinner",
        "cooking_method": "batch",
        "servings": 4,
        "prep_minutes": 15,
        "cook_minutes": 35,
        "calories": 520,
        "protein": 38.0,
        "carbs": 48.0,
        "fat": 18.0,
        "fibre": 4.0,
        "cost_per_serving": 2.50,
        "tags": ["high-protein", "freezable"],
        "instructions": "Marinate chicken in yogurt and spices. Grill or pan-fry. Simmer in sauce of tomatoes, cream and garam masala. Serve with basmati rice.",
        "ingredients": [
            ("chicken breast", 500, "g", "meat"),
            ("natural yogurt", 100, "g", "dairy"),
            ("tinned chopped tomatoes", 400, "g", "pantry"),
            ("single cream", 100, "ml", "dairy"),
            ("onion", 2, "whole", "produce"),
            ("garlic clove", 3, "whole", "produce"),
            ("fresh ginger", 20, "g", "produce"),
            ("garam masala", 2, "tsp", "spices"),
            ("ground turmeric", 1, "tsp", "spices"),
            ("ground cumin", 1, "tsp", "spices"),
            ("basmati rice", 300, "g", "pantry"),
            ("vegetable oil", 2, "tbsp", "pantry"),
        ],
    },
    {
        "name": "Beef Bolognese",
        "meal_type": "dinner",
        "cooking_method": "batch",
        "servings": 4,
        "prep_minutes": 10,
        "cook_minutes": 45,
        "calories": 520,
        "protein": 36.0,
        "carbs": 54.0,
        "fat": 16.0,
        "fibre": 5.0,
        "cost_per_serving": 2.20,
        "tags": ["high-protein", "high-iron", "freezable"],
        "instructions": "Brown mince with onion, garlic and celery. Add tomatoes, tomato purée, herbs and a splash of red wine. Simmer 40 mins. Serve with spaghetti and parmesan.",
        "ingredients": [
            ("beef mince", 500, "g", "meat"),
            ("tinned chopped tomatoes", 400, "g", "pantry"),
            ("tomato purée", 2, "tbsp", "pantry"),
            ("onion", 1, "whole", "produce"),
            ("carrot", 1, "whole", "produce"),
            ("celery stick", 1, "whole", "produce"),
            ("garlic clove", 2, "whole", "produce"),
            ("dried oregano", 1, "tsp", "spices"),
            ("spaghetti", 320, "g", "pantry"),
            ("parmesan", 40, "g", "dairy"),
            ("olive oil", 1, "tbsp", "pantry"),
        ],
    },
    {
        "name": "Chickpea & Spinach Curry",
        "meal_type": "dinner",
        "cooking_method": "batch",
        "servings": 4,
        "prep_minutes": 10,
        "cook_minutes": 25,
        "calories": 400,
        "protein": 16.0,
        "carbs": 52.0,
        "fat": 14.0,
        "fibre": 12.0,
        "cost_per_serving": 1.60,
        "tags": ["vegan", "high-fibre", "high-iron", "freezable"],
        "instructions": "Fry onion, garlic and spices. Add chickpeas, coconut milk and tomatoes. Simmer 20 mins. Stir in spinach. Serve with rice or naan.",
        "ingredients": [
            ("tinned chickpeas", 400, "g", "pantry"),
            ("coconut milk", 400, "ml", "pantry"),
            ("tinned chopped tomatoes", 400, "g", "pantry"),
            ("baby spinach", 150, "g", "produce"),
            ("onion", 1, "whole", "produce"),
            ("garlic clove", 3, "whole", "produce"),
            ("ground cumin", 2, "tsp", "spices"),
            ("ground coriander", 1, "tsp", "spices"),
            ("ground turmeric", 1, "tsp", "spices"),
            ("basmati rice", 300, "g", "pantry"),
            ("vegetable oil", 1, "tbsp", "pantry"),
        ],
    },
    {
        "name": "Chilli Con Carne",
        "meal_type": "dinner",
        "cooking_method": "batch",
        "servings": 4,
        "prep_minutes": 10,
        "cook_minutes": 40,
        "calories": 480,
        "protein": 34.0,
        "carbs": 46.0,
        "fat": 16.0,
        "fibre": 10.0,
        "cost_per_serving": 2.00,
        "tags": ["high-protein", "high-iron", "high-fibre", "freezable"],
        "instructions": "Brown mince with onion and garlic. Add kidney beans, tomatoes, chilli powder and cumin. Simmer 35 mins. Serve with rice, sour cream and grated cheese.",
        "ingredients": [
            ("beef mince", 500, "g", "meat"),
            ("tinned kidney beans", 400, "g", "pantry"),
            ("tinned chopped tomatoes", 400, "g", "pantry"),
            ("onion", 1, "whole", "produce"),
            ("garlic clove", 2, "whole", "produce"),
            ("red pepper", 1, "whole", "produce"),
            ("chilli powder", 1, "tsp", "spices"),
            ("ground cumin", 1, "tsp", "spices"),
            ("smoked paprika", 1, "tsp", "spices"),
            ("basmati rice", 300, "g", "pantry"),
            ("sour cream", 60, "g", "dairy"),
            ("cheddar cheese", 40, "g", "dairy"),
            ("vegetable oil", 1, "tbsp", "pantry"),
        ],
    },
    {
        "name": "Thai Green Chicken Curry",
        "meal_type": "dinner",
        "cooking_method": "batch",
        "servings": 4,
        "prep_minutes": 10,
        "cook_minutes": 25,
        "calories": 490,
        "protein": 36.0,
        "carbs": 48.0,
        "fat": 18.0,
        "fibre": 4.0,
        "cost_per_serving": 2.80,
        "tags": ["high-protein", "freezable"],
        "instructions": "Fry green curry paste in oil. Add chicken and brown. Pour in coconut milk, add green beans and bamboo shoots. Simmer 20 mins. Finish with Thai basil. Serve with jasmine rice.",
        "ingredients": [
            ("chicken thigh fillets", 500, "g", "meat"),
            ("green curry paste", 3, "tbsp", "pantry"),
            ("coconut milk", 400, "ml", "pantry"),
            ("green beans", 100, "g", "produce"),
            ("bamboo shoots", 100, "g", "pantry"),
            ("fish sauce", 1, "tbsp", "pantry"),
            ("brown sugar", 1, "tsp", "pantry"),
            ("jasmine rice", 300, "g", "pantry"),
            ("vegetable oil", 1, "tbsp", "pantry"),
        ],
    },
    {
        "name": "Lamb & Sweet Potato Tagine",
        "meal_type": "dinner",
        "cooking_method": "batch",
        "servings": 4,
        "prep_minutes": 15,
        "cook_minutes": 50,
        "calories": 460,
        "protein": 30.0,
        "carbs": 44.0,
        "fat": 18.0,
        "fibre": 7.0,
        "cost_per_serving": 3.50,
        "tags": ["high-protein", "high-iron", "freezable"],
        "instructions": "Brown lamb in batches. Sauté onion with spices. Return lamb, add sweet potato, apricots, stock and chickpeas. Cover and simmer 45 mins. Serve with couscous.",
        "ingredients": [
            ("diced lamb", 400, "g", "meat"),
            ("sweet potato", 300, "g", "produce"),
            ("tinned chickpeas", 200, "g", "pantry"),
            ("dried apricots", 60, "g", "pantry"),
            ("onion", 1, "whole", "produce"),
            ("garlic clove", 2, "whole", "produce"),
            ("ground cinnamon", 1, "tsp", "spices"),
            ("ground cumin", 1, "tsp", "spices"),
            ("chicken stock", 400, "ml", "pantry"),
            ("couscous", 250, "g", "pantry"),
            ("olive oil", 2, "tbsp", "pantry"),
        ],
    },
    {
        "name": "Sausage & Bean Casserole",
        "meal_type": "dinner",
        "cooking_method": "batch",
        "servings": 4,
        "prep_minutes": 10,
        "cook_minutes": 35,
        "calories": 440,
        "protein": 26.0,
        "carbs": 40.0,
        "fat": 20.0,
        "fibre": 10.0,
        "cost_per_serving": 1.80,
        "tags": ["high-fibre", "freezable"],
        "instructions": "Brown sausages, remove and slice. Sauté onion, pepper and garlic. Add beans, tomatoes, stock and herbs. Return sausages, simmer 25 mins. Serve with crusty bread.",
        "ingredients": [
            ("pork sausages", 8, "whole", "meat"),
            ("tinned cannellini beans", 400, "g", "pantry"),
            ("tinned chopped tomatoes", 400, "g", "pantry"),
            ("onion", 1, "whole", "produce"),
            ("red pepper", 1, "whole", "produce"),
            ("garlic clove", 2, "whole", "produce"),
            ("chicken stock", 200, "ml", "pantry"),
            ("dried thyme", 1, "tsp", "spices"),
            ("smoked paprika", 1, "tsp", "spices"),
            ("crusty bread", 4, "slice", "bakery"),
            ("olive oil", 1, "tbsp", "pantry"),
        ],
    },
    {
        "name": "Lentil Dal",
        "meal_type": "dinner",
        "cooking_method": "batch",
        "servings": 4,
        "prep_minutes": 10,
        "cook_minutes": 30,
        "calories": 380,
        "protein": 18.0,
        "carbs": 56.0,
        "fat": 10.0,
        "fibre": 12.0,
        "cost_per_serving": 1.20,
        "tags": ["vegan", "high-fibre", "high-iron", "freezable"],
        "instructions": "Simmer lentils in stock until tender. Fry onion, garlic, ginger and spices in oil. Stir into lentils. Finish with a squeeze of lemon. Serve with naan.",
        "ingredients": [
            ("red lentils", 250, "g", "pantry"),
            ("onion", 1, "whole", "produce"),
            ("garlic clove", 3, "whole", "produce"),
            ("fresh ginger", 20, "g", "produce"),
            ("ground turmeric", 1, "tsp", "spices"),
            ("ground cumin", 1, "tsp", "spices"),
            ("garam masala", 1, "tsp", "spices"),
            ("vegetable stock", 800, "ml", "pantry"),
            ("lemon", 0.5, "whole", "produce"),
            ("naan bread", 4, "whole", "bakery"),
            ("vegetable oil", 2, "tbsp", "pantry"),
        ],
    },
    # ── Fresh Dinners ─────────────────────────────────────────────────
    {
        "name": "Pan-Seared Salmon with New Potatoes",
        "meal_type": "dinner",
        "cooking_method": "fresh",
        "servings": 2,
        "prep_minutes": 10,
        "cook_minutes": 20,
        "calories": 500,
        "protein": 40.0,
        "carbs": 36.0,
        "fat": 22.0,
        "fibre": 5.0,
        "cost_per_serving": 4.50,
        "tags": ["high-protein", "omega-3", "gluten-free"],
        "instructions": "Boil new potatoes. Pan-sear salmon skin-down for 4 mins, flip for 2 mins. Steam asparagus. Serve with a lemon wedge.",
        "ingredients": [
            ("salmon fillet", 250, "g", "fish"),
            ("new potatoes", 300, "g", "produce"),
            ("asparagus", 150, "g", "produce"),
            ("lemon", 1, "whole", "produce"),
            ("olive oil", 1, "tbsp", "pantry"),
            ("butter", 15, "g", "dairy"),
        ],
    },
    {
        "name": "Steak with Sweet Potato Fries",
        "meal_type": "dinner",
        "cooking_method": "fresh",
        "servings": 2,
        "prep_minutes": 10,
        "cook_minutes": 25,
        "calories": 550,
        "protein": 42.0,
        "carbs": 38.0,
        "fat": 24.0,
        "fibre": 5.0,
        "cost_per_serving": 5.50,
        "tags": ["high-protein", "high-iron", "gluten-free"],
        "instructions": "Cut sweet potatoes into fries, toss in oil and bake at 200°C for 25 mins. Season steak and sear in a hot pan. Rest 5 mins. Serve with salad.",
        "ingredients": [
            ("sirloin steak", 300, "g", "meat"),
            ("sweet potato", 300, "g", "produce"),
            ("mixed salad leaves", 60, "g", "produce"),
            ("cherry tomatoes", 80, "g", "produce"),
            ("olive oil", 2, "tbsp", "pantry"),
            ("salt", 1, "pinch", "spices"),
            ("black pepper", 1, "pinch", "spices"),
        ],
    },
    {
        "name": "Prawn Stir-Fry",
        "meal_type": "dinner",
        "cooking_method": "fresh",
        "servings": 2,
        "prep_minutes": 10,
        "cook_minutes": 10,
        "calories": 400,
        "protein": 30.0,
        "carbs": 48.0,
        "fat": 10.0,
        "fibre": 4.0,
        "cost_per_serving": 3.50,
        "tags": ["high-protein", "quick"],
        "instructions": "Stir-fry prawns with garlic and ginger. Add peppers, pak choi and beansprouts. Toss with noodles, soy sauce and sesame oil.",
        "ingredients": [
            ("king prawns", 250, "g", "fish"),
            ("egg noodles", 200, "g", "pantry"),
            ("pak choi", 2, "whole", "produce"),
            ("red pepper", 1, "whole", "produce"),
            ("garlic clove", 2, "whole", "produce"),
            ("fresh ginger", 10, "g", "produce"),
            ("soy sauce", 2, "tbsp", "pantry"),
            ("sesame oil", 1, "tsp", "pantry"),
            ("vegetable oil", 1, "tbsp", "pantry"),
        ],
    },
    {
        "name": "Chicken Fajitas",
        "meal_type": "dinner",
        "cooking_method": "fresh",
        "servings": 2,
        "prep_minutes": 10,
        "cook_minutes": 15,
        "calories": 480,
        "protein": 36.0,
        "carbs": 44.0,
        "fat": 18.0,
        "fibre": 6.0,
        "cost_per_serving": 3.00,
        "tags": ["high-protein"],
        "instructions": "Slice chicken and peppers. Fry with fajita spices. Warm tortillas. Serve with guacamole, sour cream and grated cheese.",
        "ingredients": [
            ("chicken breast", 300, "g", "meat"),
            ("red pepper", 1, "whole", "produce"),
            ("yellow pepper", 1, "whole", "produce"),
            ("red onion", 1, "whole", "produce"),
            ("flour tortilla", 4, "whole", "bakery"),
            ("avocado", 1, "whole", "produce"),
            ("sour cream", 60, "g", "dairy"),
            ("cheddar cheese", 40, "g", "dairy"),
            ("lime", 1, "whole", "produce"),
            ("smoked paprika", 1, "tsp", "spices"),
            ("ground cumin", 1, "tsp", "spices"),
            ("vegetable oil", 1, "tbsp", "pantry"),
        ],
    },
    {
        "name": "Mushroom Risotto",
        "meal_type": "dinner",
        "cooking_method": "fresh",
        "servings": 2,
        "prep_minutes": 10,
        "cook_minutes": 30,
        "calories": 450,
        "protein": 14.0,
        "carbs": 62.0,
        "fat": 16.0,
        "fibre": 4.0,
        "cost_per_serving": 2.50,
        "tags": ["vegetarian"],
        "instructions": "Sauté shallot in butter. Toast arborio rice. Add hot stock a ladle at a time, stirring. Fry mushrooms separately. Fold in with parmesan.",
        "ingredients": [
            ("arborio rice", 200, "g", "pantry"),
            ("chestnut mushrooms", 200, "g", "produce"),
            ("vegetable stock", 700, "ml", "pantry"),
            ("shallot", 1, "whole", "produce"),
            ("garlic clove", 1, "whole", "produce"),
            ("parmesan", 40, "g", "dairy"),
            ("butter", 25, "g", "dairy"),
            ("dry white wine", 100, "ml", "pantry"),
            ("olive oil", 1, "tbsp", "pantry"),
        ],
    },
    {
        "name": "Grilled Sea Bass with Ratatouille",
        "meal_type": "dinner",
        "cooking_method": "fresh",
        "servings": 2,
        "prep_minutes": 15,
        "cook_minutes": 30,
        "calories": 380,
        "protein": 34.0,
        "carbs": 20.0,
        "fat": 18.0,
        "fibre": 6.0,
        "cost_per_serving": 5.00,
        "tags": ["high-protein", "omega-3", "gluten-free"],
        "instructions": "Dice courgette, aubergine and peppers. Simmer in tomatoes with garlic and herbs for 25 mins. Grill sea bass fillets skin-down for 4 mins, flip briefly. Serve on the ratatouille.",
        "ingredients": [
            ("sea bass fillets", 250, "g", "fish"),
            ("courgette", 1, "whole", "produce"),
            ("aubergine", 1, "whole", "produce"),
            ("red pepper", 1, "whole", "produce"),
            ("tinned chopped tomatoes", 400, "g", "pantry"),
            ("garlic clove", 2, "whole", "produce"),
            ("dried herbes de Provence", 1, "tsp", "spices"),
            ("olive oil", 2, "tbsp", "pantry"),
        ],
    },
]
