"""Shopping List — compact table view with PDF export."""

import io
import streamlit as st
from datetime import date

st.set_page_config(page_title="Shopping List", page_icon="\U0001F6D2", layout="wide")

from styles import inject_theme, banner, format_qty
from database import init_db, get_meal_plan, get_shopping_list
from generator import get_next_monday

inject_theme()
init_db()

banner()
st.markdown("#### \U0001F6D2 Shopping List")

# ── Week selector ─────────────────────────────────────────────────────
next_mon = get_next_monday()
week_start = st.date_input("Week starting (Monday)", value=date.fromisoformat(next_mon))
week_key = week_start.isoformat()

plan_data = get_meal_plan(week_key)
if not plan_data:
    st.warning("No meal plan for this week. Generate one in the Weekly Planner first.")
    st.stop()

plan = plan_data["plan"]
if plan["status"] == "draft":
    st.caption("Draft plan \u2014 finalise to lock your list.")
else:
    st.caption("\u2705 Finalised")

# ── Shopping list ─────────────────────────────────────────────────────
shopping = get_shopping_list(plan["id"])
if not shopping:
    st.info("No ingredients.")
    st.stop()

CATEGORY_LABELS = {
    "produce": "\U0001F966 Fresh Produce",
    "dairy": "\U0001F95B Dairy & Eggs",
    "meat": "\U0001F969 Meat",
    "fish": "\U0001F41F Fish & Seafood",
    "bakery": "\U0001F35E Bakery",
    "pantry": "\U0001F3E0 Pantry & Tins",
    "frozen": "\u2744\uFE0F Frozen",
    "spices": "\U0001F9C2 Spices & Seasoning",
    "other": "\U0001F4E6 Other",
}
CATEGORY_LABELS_PLAIN = {
    "produce": "Fresh Produce",
    "dairy": "Dairy & Eggs",
    "meat": "Meat",
    "fish": "Fish & Seafood",
    "bakery": "Bakery",
    "pantry": "Pantry & Tins",
    "frozen": "Frozen",
    "spices": "Spices & Seasoning",
    "other": "Other",
}
CATEGORY_ORDER = ["produce", "dairy", "meat", "fish", "bakery", "pantry", "frozen", "spices", "other"]

# Build HTML table + clipboard text + PDF data
html = '<table class="shop-table">'
html += "<thead><tr><th>Item</th><th>Qty</th><th>Unit</th></tr></thead><tbody>"

clipboard_lines: list[str] = []
pdf_sections: list[tuple[str, list[str]]] = []

for cat in CATEGORY_ORDER:
    cat_items = shopping.get(cat)
    if not cat_items:
        continue

    label = CATEGORY_LABELS.get(cat, cat.title())
    label_plain = CATEGORY_LABELS_PLAIN.get(cat, cat.title())
    html += f'<tr><td colspan="3" class="shop-cat-header">{label}</td></tr>'
    clipboard_lines.append(f"\n{label_plain}")

    section_lines: list[str] = []
    for item in sorted(cat_items, key=lambda x: x["ingredient"]):
        qty = item["quantity"]
        unit = item["unit"] or ""
        name = item["ingredient"]
        qty_str = str(int(qty)) if qty == int(qty) else f"{qty:.1f}"

        html += f"<tr><td>{name.title()}</td><td>{qty_str}</td><td>{unit}</td></tr>"

        line = format_qty(qty, unit, name)
        clipboard_lines.append(f"  {line}")
        section_lines.append(f"  {line}")

    pdf_sections.append((label_plain, section_lines))

html += "</tbody></table>"
st.markdown(html, unsafe_allow_html=True)

# ── Export row ────────────────────────────────────────────────────────
st.markdown("---")
clipboard_text = "\n".join(clipboard_lines)

col_a, col_b, col_c = st.columns(3)

with col_a:
    st.download_button(
        "\U0001F4CB Copy as text",
        data=clipboard_text,
        file_name=f"shopping_{week_key}.txt",
        mime="text/plain",
        use_container_width=True,
    )

with col_b:
    # PDF export
    try:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # Title
        pdf.set_font("Helvetica", "B", 16)
        pdf.set_text_color(173, 20, 87)
        pdf.cell(0, 10, "Meal Planning Amp - Shopping List", ln=True, align="C")
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 7, f"Week of {week_key}", ln=True, align="C")
        pdf.ln(4)

        for section_name, section_items in pdf_sections:
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(173, 20, 87)
            pdf.cell(0, 8, section_name, ln=True)

            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(50, 50, 50)
            for line in section_items:
                pdf.cell(6, 5, "[ ]", ln=False)
                pdf.cell(0, 5, line.strip(), ln=True)
            pdf.ln(2)

        # Footer
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(180, 180, 180)
        pdf.cell(0, 10, "Generated by Meal Planning Amp", ln=True, align="C")

        pdf_bytes = pdf.output()

        st.download_button(
            "\U0001F4C4 Export PDF",
            data=bytes(pdf_bytes),
            file_name=f"shopping_{week_key}.pdf",
            mime="application/pdf",
            use_container_width=True,
        )
    except ImportError:
        st.caption("Install `fpdf2` for PDF export: `pip install fpdf2`")

with col_c:
    st.text_area("Plain text", value=clipboard_text, height=150, label_visibility="collapsed")
